### ISSUE TITLE
Implement Ledger auth method

### ISSUE THREAD

**Issue by razvanstatescu** [Elrond-Giants/erd-next-starter#2]
We'll need to also add the Ledger auth method. Until then, users that want to connect using Ledger can do this using the Web Wallet.

**Comment by filipac** [comment]
Started writing it but don't have time to finish :( this would be really helpful indeed

**Comment by razvanstatescu** [comment]
> Started writing it but don't have time to finish :( this would be really helpful indeed

We'll include it in the next release.

**Comment by razvanstatescu** [comment]
It's included now. 🎉
